apiVersion: v1
kind: Secret
metadata:
    name: my-app-secret
type: Opaque
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:ISqy0ArHnDFLGg==,iv:ENMNhQAJoIJFigYz0ArqmiqLAadBfnJsClehVxpqm8s=,tag:+HykaDA6jF02Qg5e/BxmZg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-west-3:041534130393:key/64f85c73-c04d-45d9-8777-3458dcc52b5c
          created_at: "2025-04-28T12:07:26Z"
          enc: AQICAHhAVgSnaVH0lfgOS/xAJbB276HZKlhZyJ/gqn2YvcR+twHr1C9PPkinrTkrsbxp/WUkAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMgO+CaRSpEJAV92WoAgEQgDvJKpdoBxzV8MeyD6PzgRY9nwi8RY5SfSPLvyymrSFaD/oWjI0/iFmTIPtKz6xxn8NgK+ZRyPn4HFX5GA==
          aws_profile: ""
    lastmodified: "2025-04-28T12:07:26Z"
    mac: ENC[AES256_GCM,data:reoCeYde3GI2z/WI/zpKsh2e2htqvdeV5yIQzzW3mb9Rz7Ti1xpdOnBzYSvKqjIanQTbP8nY6rtzcpAFhA3DDUmU30289NiF4KSJ5cJC61JNd+C5/EcCISTPngzpX4mO+pS4YWtzep5+q7q6DnRTg2fbd09Ns30O1yJUO4ov3o4=,iv:+G1v80wJ+m9MwTRdsFFfb5MOUqaXzr8oIAo7lsHrTCc=,tag:iuJ6xMTMagCCpIQcKy0dPA==,type:str]
    encrypted_regex: ^(data|stringData|secrets?)$
    version: 3.10.2
