# secrets.enc.yaml
apiVersion: v1
kind: Secret
metadata:
  name: my-app-secret
type: Opaque
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:z51tK/Xrbq2p9kU4Y0Y=,iv:gLp26mDaeKrvB/pr0eWypkrCykRjmzLZI0u8TXbbT68=,tag:o6BK8G74fctP1ve0ywZzRg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-west-3:461536490486:key/73a9eee5-f455-48fd-ab4a-95f39c154401
          created_at: "2025-04-09T14:41:59Z"
          enc: AQICAHhZkvW8z1UzlhS7KXuIDIU9YaP0VsnTtJAURULKWSiR9gEuTKPgz3pMcC1jfEoOSX7EAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMG4CxyCaXRgKmvaAsAgEQgDtcnolzmCsOIGZ06vuewcENzCx68RnFMLHR4HzEL6sSfsDLU0GIQQ8qyO8vXuJRvxCMre76v1BvGI831g==
          aws_profile: ""
    lastmodified: "2025-04-09T14:42:00Z"
    mac: ENC[AES256_GCM,data:17dqRtqzyB7yMvAjN42eDQ3+OEMTkZLjuY6sViu8dv74IThlcJHGPOKOS5ym5l+tMfofqbsc8clEsH6o5H/9Ntt5oTCcuQ2EStJa5nSmbg1sbWtSa1aPsfjR/RFtKDRKvndugSHylOgecjkiRtBsOd2ns65vv23ZHSzrjnOpHOk=,iv:VZ1v+7uE8E8vJrt0lXx3cLTrf1iDjmWSLGztjDr23S8=,tag:xW9e5V7jF1kKxGQ5W4S0UA==,type:str]
    encrypted_regex: ^(data|stringData|secrets?)$
    version: 3.10.1
